---
- hosts: all
  tasks:
    - name: 'setup'
      setup:
        filter: '*'
      tags:
        - always

- hosts: application
  become: true
  roles:
    - { role: authorities, tags: [ 'authorities' ] }
