---
## The command is:

- hosts: all
  tasks:
    - name: 'setup'
      setup:
        filter: '*'
      tags:
        - always

- hosts: application
  become: true
  roles:
    - { role: import, tags: [ 'import' ] }
