---
## The command is then:
## ansible-playbook -vv -i oicr-inventory.ini --connection=ssh --become-method=sudo --extra-vars=import_directory=/... import.yml

- hosts: application
  tasks:
    - name: 'setup'
      setup:
        filter: '*'

- hosts: application
  become: true
  roles:
    - { role: import, tags: [ 'import' ] }
