---

- hosts: all
  tasks:
    - name: 'setup'
      setup:
        filter: '*'
      tags:
        - always

- hosts: database
  become: true
  roles:
    - { role: database, tags: [ 'database' ] }

- hosts: application
  become: true
  roles:
    - { role: cbioportal, tags: [ 'cbioportal' ] }
