---
- name: cBioPortal import | ensure the staging directory exists
  file:
    path: "{{remote_staging}}"
    state: directory

- name: cBioPortal import | clear out old import data
  command: rm -rf "{{remote_staging}}"

- name: cBioPortal import | clear out old import data
  file:
    state: directory
    path: "{{remote_staging}}"

# We might fail here if we don't have a directory of data
- name: cBioPortal import | copy over staging data
  copy:
    src: "{{import_directory}}/"
    dest: "{{remote_staging}}/"

- name: cBioPortal import | import the data
  shell: >
    env PORTAL_HOME={{webapp_directory}} java -cp scripts-`cat build.project.version`.jar:cbioportal-importer-`cat build.importer.version`.jar ca.uhnresearch.pughlab.cbioportal.scripts.ImportWrapper {{remote_staging}} cbioportal-import.xml
    chdir="{{webapp_directory}}"

- name: cBioPortal import | restart the web application
  service: name={{webapp_service_name}} state=restarted enabled=yes
