---
- name: Jetty | Download Jetty
  get_url:
    dest: '{{jetty_target}}'
    url: '{{jetty_url}}'

- name: Jetty | Write service configuration files
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  notify:
    - restart service
  with_items:
    - { src: "jetty.xml.j2", dest: "{{webapp_directory}}/{{webapp_service_name}}.xml", mode: '0755' }
    - { src: "jetty.init.j2", dest: "/etc/init.d/{{webapp_service_name}}", mode: '0755' }
