---
- name: Java | Install OpenJDK runtime
  apt: pkg=openjdk-8-jre-headless state=present update_cache=yes cache_valid_time=3600

- name: Java | Install OpenJDK Java developer kit
  apt: pkg=openjdk-8-jdk state=present update_cache=yes cache_valid_time=3600

- name: Java | Install IcedTea plugin
  apt: pkg=icedtea-8-plugin state=present update_cache=yes cache_valid_time=3600

- name: Java | Set default Java
  shell: update-java-alternatives --set java-1.8.0-openjdk-amd64
