---
- name: cBioPortal | Install git
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
  - git
  - maven

- include: 'build_cbioportal.yml'
- include: 'build_cbioportal_importer.yml'
- include: 'build_cbioportal_overlay.yml'
- include: 'deploy.yml'

- name: cBioPortal | ensure the service is running
  service: name={{webapp_service_name}} state=restarted enabled=yes
