---
oidc_repository: 'https://github.com/morungos/openid-connect-server'
oidc_version: '1.1.0-RC1'
oidc_release: '{{oidc_repository}}/releases/download/{{oidc_version}}'
oidc_url: '{{oidc_release}}/openid-connect-server-{{oidc_version}}.war'

oidc_database_host: '{{mysql_database_host}}'
oidc_database_port: 3306
oidc_database_name: 'oidc'
oidc_database_username: 'oidc'
oidc_database_password: 'oidc'

oidc_admin_username: 'stuartw'

oidc_config_issuer: "http://localhost:8080/oidc/"
oidc_config_logo_image_url: "resources/images/full_uhn_logo.png"
oidc_config_topbar_title: "UHN OpenID Connect Server"

oidc_ldap_providers:
  - class: 'org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider'
    name: "researchAuthProvider"
    arguments:
      - name: domain
        value: "ads.uhnresearch.ca"
      - name: url
        value: "ldap://192.168.198.100"

authentication_portal_settings:
  'authenticate': 'openid-connect'
  'authorization': 'true'
  'oidc.adminSubject': '{{oidc_admin_username}}'
  'oidc.issuer': "{{webapp_external_base}}/oidc"
  'oidc.clientId': '{{oidc_application_client_id}}'
  'oidc.clientSecret': '{{oidc_application_secret}}'
  'oidc.redirect': "{{webapp_external_base}}/login"
