---
mysql_root_password: 'f3042dfb0da5'
mysql_database_host: 'localhost'
mysql_database_port: '3306'
mysql_database_name: 'cbioportal'
mysql_database_user: 'cbioportal'
mysql_database_password: 'cbioportal'
mysql_test_database_name: 'cgds_test'
mysql_application_host: 'localhost'

oidc_database_host: '{{mysql_database_host}}'
oidc_database_port: 3306
oidc_database_name: 'oidc'
oidc_database_username: 'oidc'
oidc_database_password: 'oidc'

default_portal_settings:
  'db.user': "{{mysql_database_user}}"
  'db.password': "{{mysql_database_password}}"
  'db.host': "{{mysql_database_host}}"
  'app.name': "cBioPortal"
  'db.connection_string': "jdbc:mysql://{{mysql_database_host}}:3306/{{mysql_database_name}}"
  'mycancergenome.show': "false"
  'dbconnector': 'jndi'

portal_settings: {}
