---
mysql_root_password: 'f3042dfb0da5'
mysql_database_host: 'localhost'
mysql_database_port: '3306'
mysql_database_name: 'cbioportal'
mysql_database_user: 'cbioportal'
mysql_database_password: 'cbioportal'
mysql_test_database_name: 'cgds_test'
mysql_application_host: 'localhost'
